package com.sony.dpt.override;

public interface UpdateMode {
    int EINK_CONVERT_MODE_CONVERT = 1024;
    int EINK_CONVERT_MODE_MASK = 1024;
    int EINK_CONVERT_MODE_NOCONVERT = 0;
    int EINK_SP1_1 = 4096;
    int EINK_SP1_1_MASK = 4096;
    int EINK_SP1_2 = 8192;
    int EINK_SP1_2_MASK = 8192;
    int EINK_SP1_IGNORE = 16384;
    int EINK_SP1_IGNORE_MASK = 16384;
    int EINK_UPDATE_MODE_FULL = 32;
    int EINK_UPDATE_MODE_MASK = 32;
    int EINK_UPDATE_MODE_PARTIAL = 0;
    int EINK_WAIT_MODE_MASK = 64;
    int EINK_WAIT_MODE_NOWAIT = 0;
    int EINK_WAIT_MODE_WAIT = 64;
    int EINK_WAVEFORM_MODE_A2 = 4;
    int EINK_WAVEFORM_MODE_DU = 1;
    int EINK_WAVEFORM_MODE_DU3 = 6;
    int EINK_WAVEFORM_MODE_DU4 = 5;
    int EINK_WAVEFORM_MODE_GC16 = 2;
    int EINK_WAVEFORM_MODE_GL16 = 3;
    int EINK_WAVEFORM_MODE_INIT = 0;
    int EINK_WAVEFORM_MODE_MASK = 15;
    int UI_DEFAULT_MODE = 2;

    int UPDATE_MODE_UI_DEFAULT = EINK_WAVEFORM_MODE_GC16 | EINK_CONVERT_MODE_NOCONVERT | EINK_UPDATE_MODE_PARTIAL | EINK_WAIT_MODE_NOWAIT; // 2
    int UPDATE_MODE_CONVERT_A2_PARTIAL = EINK_WAVEFORM_MODE_A2 | EINK_CONVERT_MODE_CONVERT | EINK_UPDATE_MODE_PARTIAL | EINK_WAIT_MODE_NOWAIT; // 1028
    int UPDATE_MODE_NOWAIT_CONVERT_DU = EINK_WAVEFORM_MODE_DU | EINK_CONVERT_MODE_CONVERT | EINK_WAIT_MODE_WAIT; // 1025
    int UPDATE_MODE_NOWAIT_CONVERT_DU_SP1_IGNORE = 17409;
    int UPDATE_MODE_NOWAIT_DU = EINK_WAVEFORM_MODE_DU | EINK_WAIT_MODE_NOWAIT | EINK_UPDATE_MODE_PARTIAL; // 1
    int UPDATE_MODE_NOWAIT_GC16 = EINK_WAVEFORM_MODE_GC16 | EINK_UPDATE_MODE_FULL | EINK_WAIT_MODE_NOWAIT; //34;
    int UPDATE_MODE_NOWAIT_GC16_FULL_SP1_SP2 = 12322;
    int UPDATE_MODE_NOWAIT_GC16_PARTIAL = EINK_WAVEFORM_MODE_GC16 | EINK_UPDATE_MODE_PARTIAL | EINK_WAIT_MODE_NOWAIT; // 2
    int UPDATE_MODE_NOWAIT_GC16_PARTIAL_SP1_IGNORE = 16386;
    int UPDATE_MODE_NOWAIT_GC16_PARTIAL_SP1_SP2 = 12290;
    int UPDATE_MODE_NOWAIT_GC16_PARTIAL_SP2_IGNORE = 24578;
    int UPDATE_MODE_NOWAIT_GC16_SP2 = 8226;
    int UPDATE_MODE_NOWAIT_NOCONVERT_DU_SP1_IGNORE = 16385;
}
